export const testimonials = [
  {
    id: 1,
    name: "Deer aaasas",
    comment: "tempatnya asik",
    time: "2 Days Ago",
    rating: 3.5,
    img: "image1",
  },
  {
    id: 2,
    name: "Deer aaasas",
    comment: "lumayan nyaman",
    time: "3 Days Ago",
    rating: 4,
    img: "image2",
  },
  {
    id: 3,
    name: "uhuy",
    comment: "tempatnya asik UPDATE",
    time: "3 Days Ago",
    rating: 3,
    img: "image3",
  },
  {
    id: 4,
    name: "uhuy",
    comment: "tempatnya asik UPDATE",
    time: "5 Days Ago",
    rating: 4,
    img: "image4",
  },
  {
    id: 5,
    name: "Jasmine",
    comment: "Tempatnya asik ges",
    time: "Today",
    rating: 4.5,
    img: "image5",
  },
  {
    id: 6,
    name: "Salsa",
    comment: "Tempatnya mudah di booking",
    time: "1 weeks Ago",
    rating: 5,
    img: "image6",
  },
  {
    id: 7,
    name: "Dion",
    comment: "Wah keren abiss sih ini tempatnya",
    time: "1 Days Ago",
    rating: 4.5,
    img: "image7",
  },
  {
    id: 8,
    name: "Bernadi",
    comment: "Aplikasi nya keren, fiturnya bagus",
    time: "1 Days Ago",
    rating: 4.5,
    img: "image8",
  },
  {
    id: 9,
    name: "Deer aaasas",
    comment: "ruangannya panas",
    time: "1 Days Ago",
    rating: 1,
    img: "image9",
  },
  {
    id: 10,
    name: "Layla",
    comment: "Tempatnya bagus bagus",
    time: "2 Days Ago",
    rating: 4.5,
    img: "image10",
  },
];
